### ISSUE TITLE
Help Test RailsInstaller Beta With Ruby 2.4

### ISSUE THREAD

**Issue by crigor** [railsinstaller/railsinstaller-windows#103]
RailsInstaller now has Ruby 2.4 using RubyInstaller2. It is bigger at 214mb because RubyInstaller2 uses msys2, which I've included to get a Rails environment out of the box.

Please help test this beta version and provide feedback here. An official version will be released after Rails 5.2 is released (which is now in beta).

Link: https://s3.amazonaws.com/railsinstaller-betas/railsinstaller-5.2.0.beta1.exe
MD5 Checksum: 40ea0fd5681df8a4e898ce87ae080781

After installing, a cmd.exe will open just like in previous versions. A sample Rails 5.2.0.beta1 is included.

Rails and other gems are preinstalled so you can run `rails server` after installation.

```
cd C:\Sites\sampleapp5.2.0.beta1
bundle exec rails server
```

**Comment by RacerRex** [comment]
Running on Win7 Enterprise SP1, 64-bit. Initial installation failed due to Git installation.

* Downloaded installer and validated MD5
* Clicked "I accept" and Next
* Left defaults (which includes Install Git) then clicked Install
* Install begins then clicked Finish with Configure Git checked (default)
* cmd windows comes up and gives this output:
 \# Rails Environment Configuration.
C:/RailsInstaller/scripts/config_check.rb:28:in ``': No such file or directory -
 C:/RailsInstaller/Git/bin/ssh-keygen.exe -f "C:\Users\80005152/.ssh/id_rsa" -t
rsa -b 2048 -N "" -C "[user name] <[email address]>" (Errno::ENOENT)
        from C:/RailsInstaller/scripts/config_check.rb:28:in `run'
        from C:/RailsInstaller/scripts/config_check.rb:32:in `generate_ssh_key'
        from C:/RailsInstaller/scripts/config_check.rb:65:in `<main>'

config_check.rb points to ssh-keygen.exe which doesn't exist. Installing either without Git or with Git but Config Git unchecked installs without error. Have not yet tested past this point.

**Comment by crigor** [comment]
Thank you for the report @RacerRex. 

I used a new Git package from https://gitforwindows.org/ on railsinstaller-5.2.0.beta1.exe. ssh-keygen.exe is on a different location. 

The previous Git version seems to be https://github.com/msysgit/msysgit which is discontinued. They suggest using Git For Windows.

I'll update config_check.rb. But this error shouldn't cause any problems with running Rails apps.

**Comment by robertmabbs** [comment]
A new version of RailsInstaller has been released.
