### ISSUE TITLE
Rails - The system cannot find the path specified

### ISSUE THREAD

**Issue by askeroff** [railsinstaller/railsinstaller-windows#73]
I have installed rails and ruby with railsinstaller. The problem is, when i run rails command, it gives me: "The system cannot find the path specified."

I am running windows 7 x64. Ruby 2.20

Tried uninstalling rails and installing it againt, does not help. Ruby commands executes like "ruby -v", "rails -v" doesn`t work.

Have googled,didn`t find solution for windows, that worked. I have uninstalled it and installed it, I don`t know whats happening.
Ruby is in an environment path, so it executes rails with "rails -v", but gives me that message.
Someone help, please.

**Comment by j54n1n** [comment]
I encountered the same problem. I used the latest railsinstaller version 3.2.0 and I discovered that in the install path C:\RailsInstaller\Ruby2.2.0\bin some of the batch (*.bat) files contained a wrong path.
Instead of the string `@"C:\Users\emachnic\GitRepos\railsinstaller-windows\stage\Ruby2.2.0\bin\ruby.exe"` the files should contain something like `@"%~dp0ruby.exe"`.

A temporary fix is to replace any string containing `@"C:\Users\emachnic\GitRepos\railsinstaller-windows\stage\Ruby2.2.0\bin\ruby.exe"` with `@"%~dp0ruby.exe"` after the line with `:WinNT`.

**Comment by askeroff** [comment]
@j54n1n , wow, changing path inside batch file worked. Did not know, I could do that. Been struggling with it whole day.Thanks a lot.

**Comment by emachnic** [comment]
Closed at dup of #70

**Comment by aheshan** [comment]
This helps me too on windows. The path was incorrect in bath file.

**Comment by BelieveC** [comment]
Thanxxx... A lottt! Saved a loottt of time

**Comment by priyansh1990** [comment]
@j54n1n "some of the batch" please you explicitly define the batch files which require change.

**Comment by hope2332** [comment]
Thanks j5414, that did the trick for me and I only had to spend 10 minutes doing it!

**Comment by JP-x** [comment]
@priyansh1990 

From what I determined sadly, was that you have to go through each of the batch files  within the C:\RailsInstaller\Ruby2.2.0\bin directory. 

In my case I went to bundle and bundler batch files since they were the commands that were not working.

**Comment by jayantbh** [comment]
I opened all the files under **C:\RailsInstaller\Ruby2.2.0\bin** in **Sublime Text**, and replaced with `Ctrl+Shift+F`,
This
`@"C:\Users\emachnic\GitRepos\railsinstaller-windows\stage\Ruby2.2.0\bin\ruby.exe"`
with this
`@"%~dp0ruby.exe"`
across all files that had a match.

Took only a couple of seconds. This might help someone who stumbles across it after me.

**Comment by ziezam** [comment]
thanks , its work

**Comment by Ericean** [comment]
@jayantbh  thanks a lot, it really saves my time!

**Comment by susantabiswas** [comment]
thanks a lot!!

**Comment by vinaymopidevi** [comment]
great thank you

**Comment by vinaymopidevi** [comment]
updated rails.bat
=======================================================================
@ECHO OFF
IF NOT "%~f0" == "~f0" GOTO :WinNT
@"%~dp0ruby.exe" "C:/Users/emachnic/GitRepos/railsinstaller-windows/stage/Ruby2.2.0/bin/rails" %1 %2 %3 %4 %5 %6 %7 %8 %9
GOTO :EOF
:WinNT
@"%~dp0ruby.exe" "%~dpn0" %*

**Comment by neohunter** [comment]
Why this is closed? whats the purpuse of including a wrong path?

**Comment by deepankar30052** [comment]
Solved the problem .  Thanks

**Comment by ArthurZ** [comment]
It is still a problem, just saying please do not give up on Windows users.

**Comment by emachnic** [comment]
I don't know how to fix this. If anyone knows a Windows dev who might be
able to help, it would be much appreciated.

Evan

**Comment by RyanSpears** [comment]
The solution by vinaymopidevi solved the problem for me too.

**Comment by SamKeightley** [comment]
Solved the problem. Is there no way to fix this?

**Comment by SaqlainGardezi** [comment]
where could i find my .bat file?

**Comment by thanhquang1988** [comment]
it work. thanks
I opened all the files under C:\RailsInstaller\Ruby2.2.0\bin in Sublime Text, and replaced with Ctrl+Shift+F,
This
@"C:\Users\emachnic\GitRepos\railsinstaller-windows\stage\Ruby2.2.0\bin\ruby.exe"
with this
@"%~dp0ruby.exe"
across all files that had a match.

**Comment by ninoM** [comment]
Just replacing it with this:
@"%~dp0ruby.exe"
didn't work for me. rails -v was working for me though and it was "bundle install" that wasn't working so I went into rails.bat and copied the line below :WinNT and this is what I found
@"C:\RailsInstaller\Ruby2.2.0\bin\ruby.exe" "%~dpn0" %*

which I copy pasted to the bundle.bat and bundler.bat and it worked! Hope this helps someone else.

**Comment by johnescobia** [comment]
Worked for me! Thanks heaps!

**Comment by webdril** [comment]
@jayantbh you really saved me...God bless you,your effort and others in this room

**Comment by valkyrea** [comment]
Worked for me, as well!!! Thank you!!!!!!

**Comment by mixelpixel** [comment]
Sorry, but I know nothing of Windows batch files (*.bat).

Instead of this:
@ECHO OFF
IF NOT "%~f0" == "~f0" GOTO :WinNT
@"C:\Users\emachnic\GitRepos\railsinstaller-windows\stage\Ruby2.2.0\bin\ruby.exe" "C:/Users/emachnic/GitRepos/railsinstaller-windows/stage/Ruby2.2.0/bin/bundle" %1 %2 %3 %4 %5 %6 %7 %8 %9
GOTO :EOF
:WinNT
@"C:\Users\emachnic\GitRepos\railsinstaller-windows\stage\Ruby2.2.0\bin\ruby.exe" "%~dpn0" %*

Do we want this:
@ECHO OFF
IF NOT "%~f0" == "~f0" GOTO :WinNT
@"%~dp0ruby.exe" **"C:/Users/emachnic/GitRepos/railsinstaller-windows/stage/Ruby2.2.0/bin/rails"** %1 %2 %3 %4 %5 %6 %7 %8 %9
GOTO :EOF
:WinNT
@"%~dp0ruby.exe" "%~dpn0" %*

or

@ECHO OFF
IF NOT "%~f0" == "~f0" GOTO :WinNT
@"%~dp0ruby.exe" **"%~dp0ruby.exe"** %1 %2 %3 %4 %5 %6 %7 %8 %9
GOTO :EOF
:WinNT
@"%~dp0ruby.exe" "%~dpn0" %*

**Comment by mixelpixel** [comment]
I also ask because in addition to the ruby.exe installed from http://railsinstaller.org/en
ruby **2.2.4**p230 (2015-12-16 revision 53155) [i386-mingw32]
installed at C;/RailsInstaller/bin/

I also have more recent ruby.exe from http://rubyinstaller.org/downloads/
ruby **2.3.1**p112 (2016-04-26 revision 54768) [x64-mingw32]
installed at C:/Ruby23-x64/bin/
and need to use it in conjunction with gems that require this newer version.

Will I need to also modify the .bat files in Ruby 2.3.?

Of note, there are only two:
setrbvars.bat
rake.bat

and rake.bat read:
@ECHO OFF
IF NOT "%~f0" == "~f0" GOTO :WinNT
ECHO.This version of Ruby has not been built with support for Windows 95/98/Me.
GOTO :EOF
:WinNT
@"%~dp0ruby.exe" "%~dpn0" %*

**Comment by giathanhphat** [comment]
it's work. Thank so much.

**Comment by icecoldbear** [comment]
Go into C:\RailsInstaller\Ruby2.2.0. Change all contents in the .bat files from this:
@ECHO OFF
IF NOT "%~f0" == "~f0" GOTO :WinNT
@"C:\Users\emachnic\GitRepos\railsinstaller-windows\stage\Ruby2.2.0\bin\ruby.exe" "C:/Users/emachnic/GitRepos/railsinstaller-windows/stage/Ruby2.2.0/bin/tilt" %1 %2 %3 %4 %5 %6 %7 %8 %9
GOTO :EOF
:WinNT
@"C:\Users\emachnic\GitRepos\railsinstaller-windows\stage\Ruby2.2.0\bin\ruby.exe" "%~dpn0" %*

Delete that and paste in the text below:

@ECHO OFF
IF NOT "%~f0" == "~f0" GOTO :WinNT
ECHO.This version of Ruby has not been built with support for Windows 95/98/Me.
GOTO :EOF
:WinNT
@"%~dp0ruby.exe" "%~dpn0" %*

**Comment by RyanSpears** [comment]
Not sure if anyone is interested, but I did not have to worry about any of the above when I followed the following to install ruby and rails on Windows. http://railsinstallfest.org/guides/installfest/rails_on_windows/

**Comment by MrWillowy** [comment]
Thanks alot! 

I opened C:\RailsInstaller\Ruby2.3.0\bin\rails.bat and replaced all @"C:\Users\emachnic\GitRepos\railsinstaller-windows\stage\Ruby2.2.0\bin\ruby.exe" with @"%~dp0ruby.exe" works perfect now.

**Comment by MrWillowy** [comment]
Thanks alot! 

I opened C:\RailsInstaller\Ruby2.3.0\bin\rails.bat with Sublime Text and replaced all @"C:\Users\emachnic\GitRepos\railsinstaller-windows\stage\Ruby2.2.0\bin\ruby.exe" with @"%~dp0ruby.exe" works perfect now.

**Comment by JenerikMind** [comment]
Used vinaymopidevi's updated Rails.bat, re-ran the batch file and fixed it up in a jiffy.  Fantastic.

**Comment by Adilkemo** [comment]
**fixing rails problem on windwos 7, 8, 10:**

I have been faced a lot of problems while I'm trying to run rails on my system, I try many solutions to solve, but all comes under failed. So, now I got one solution work good on my system, I recommend you to try this with steps it may can help you too.

Download the "rubyinstall" and run on your System, Then Download "Devekite" for ruby extract on folder “C:\RubyDevKit“ after you do this.

Now come to Command ruby type:
C:\Users>cd..
C:\>cd C:\RubyDevKit
C:\RubyDevKit>chcp 1252
C:\RubyDevKit>ruby dk.rb init
C:\RubyDevKit>ruby dk.rb install
C:\RubyDevKit>gem install rails --version 5.0.0
C:\RubyDevKit>rails -v
C:\RubyDevKit>cd..
C:\>cd [folder_name]
C:\[folder_name]>rails new sample_app
C:\[folder_name]>bundle install
C:\[folder_name]>rails server   or  rails s

**Comment by nabucodonosor7** [comment]
muchas gracias me ayudaron muchisimo
